
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvuwhkaxrwrdgydxvprr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dXdoa2F4cndyZGd5ZHh2cHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzUxMTQsImV4cCI6MjA2MTU1MTExNH0.w4tkJ4MrU9cMaBAsBIzA6tuHe2AwQ94J3AkT67h43uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Ensure we're using the most reliable configuration for auth
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'digiurban-auth-storage',
      storage: typeof window !== 'undefined' ? localStorage : undefined
    }
  }
);
