
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.NEXT_PUBLIC_SUPABASE_URL || "http://82.25.69.57:8186";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlLWluc3RhbmNlLW1hbmFnZXIiLCJpYXQiOjE3NTM1NjEwOTMsImV4cCI6MTc4NTA5NzA5M30.snWq7pI3NRlMZ4crZt030F8ws4mFQDddnaEIT3d4Y-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Ensure we're using the most reliable configuration for auth
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'digiurban-auth-storage',
      storage: typeof window !== 'undefined' ? localStorage : undefined
    }
  }
);
